upstream django {
    server web:8000;
}

server {
    listen 80;
    server_name proton2.uz www.proton2.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name proton2.uz www.proton2.uz;

    ssl_certificate /etc/letsencrypt/live/proton2.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/proton2.uz/privkey.pem;

    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
    }
}
