# Generated by Django 5.0.1 on 2026-05-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
