# Generated by Django 6.0.2 on 2026-02-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_card_transaction', to='accounts.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_card_transaction', to='accounts.card')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
