# Generated by Django 6.0.2 on 2026-03-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tranzaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='tranzaction',
        ),
    ]
